application: sim-solar
version: 2
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /css
  static_dir: assets/css

- url: /js
  static_dir: assets/js

- url: /fonts
  static_dir: assets/fonts

- url: /images
  static_dir: assets/images

- url: /.*
  script: main.application


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: endpoints
  version: latest
